import type { Metadata } from "next";
import localFont from "next/font/local";
import { Roboto } from "next/font/google";
import "./globals.css";
// import { cn } from "@/lib/utils";
import ArrowUp from "@/components/atoms/ArrowUp/ArrowUp";
import Topbar from "@/components/organisms/Topbar/Topbar";
import Footer from "@/components/organisms/FooterSection/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

const roboto = Roboto({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto",
  weight: ["100", "300", "400", "500", "700", "900"], // Specify font weights
});

export const metadata: Metadata = {
  title: "Cleaning App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable}  ${roboto.variable} antialiased`}
        // className={cn("text-foreground antialiased", roboto.variable)}
      >
        <div className="mb-20 md:mb-24">
          <Topbar />
        </div>
        {children}
        <ArrowUp />
        <Footer />
      </body>
    </html>
  );
}
